### ISSUE TITLE
Is it possible to create buttons whose content updates based on a web api

### ISSUE THREAD

**Issue by yogiben** [madriska/react-native-quick-actions#48]
Use case: we want to show bitcoin price in quick action menu. This would require an http call.

Is it possible to show a loading indicator, make a request then show the bitcoin price?

**Comment by jordanbyron** [comment]
Hi @yogiben!

This seems more like a question better suited for [StackOverflow](https://stackoverflow.com/questions/tagged/react-native) rather than our bug tracker. If you think there is a defect in react-native-quick-actions or a feature that could be added to allow for the type of workflow you are suggesting then this is the right place. Best of luck! 🐎
